### ISSUE TITLE
1.1 📁Страница с колодами

### ISSUE THREAD

**Issue by LaV0n** [LaV0n/project1#7]
- [x] 1) Отрисовка таблицы с колодами

   

- [x]  2) Реализовать добавление новой колоды

    

- [x] 3) Реализовать возможность удаления колоды

  

- [x]   4) Реализовать возможность редактирования колоды

**Comment by AlexanderLukomsky** [comment]
added CRUD operations

**Comment by AlexanderLukomsky** [comment]
completed
